[tool.poetry]
name = "morecopy"
version = "0.1.0"
description = "Copy even immutable objects as much as possible"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.9b"
flake8 = "^4.0"
ipython = "^7.28"
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
